[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
